### PR TITLE
Add topic management functions.

### PR DESCRIPTION
**Pull request by conormcd**
Add the following functions to gregor.core:

- `create-topic` - Create a new Kafka topic.
- `topic-exists?` - Check if a topic exists.
- `delete-topic` - Delete an already-existing topic.

### CODE REVIEW

**Comment by ccann** [comment]
This is great. The scope of this library is pretty minimal but I think topic management makes a lot of sense to add.

**Comment by conormcd** [comment]
Thanks!

**Comment by ccann** [comment]
Any interest @conormcd in making this compatible with kafka 10? Looks like createTopic's arity has changed, for one.

**Comment by conormcd** [comment]
@ccann Done! https://github.com/weftio/gregor/pull/11

**Pull request merged**
