### PR TITLE
Add byte array (de)serializer

### PR DESCRIPTION
**Pull request by vrih**
Just adds a couple of lines for byte array serializing. We need this for handling protobuf messages.

### CODE REVIEW

**Comment by ccann** [comment]
Great! One of them is supposed to be a serializer, though, right? Fix and I'll merge 👍 

You can also just pass in the desired (de)serializer class via the config map to `consumer` e.g. 
`{"key.deserializer" "org.apache.kafka.common.serialization.ByteArrayDeserializer"}`

**Comment by vrih** [comment]
Updated.

Also, thanks for putting this together. Getting really good performance for nearly no code out of this.

**Comment by ccann** [comment]
Glad to hear it!

**Comment by Poogles** [comment]
@ccann Do you mind releasing a new version with this included?

**Comment by ccann** [comment]
I'll do a `0.3.1` release today or tomorrow; in the meantime you should be able to use the approach above :-)

**Pull request merged**
